kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-service: conditions-api
  name: conditions-api
spec:
  ports:
    - name: conditions-api
      port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    k8s-service: conditions-api
