apiVersion: v1
data:
  config.yaml: aXNzdWVyOiBodHRwOi8vMC4wLjAuMDo1NTU2L2RleAp3ZWI6CiAgaHR0cDogMC4wLjAuMDo1NTU2CiMgU2VlIGh0dHBzOi8vZGV4aWRwLmlvL2RvY3Mvc3RvcmFnZS8gZm9yIG1vcmUgb3B0aW9ucwpzdG9yYWdlOgogIHR5cGU6IG1lbW9yeQpsb2dnZXI6CiAgbGV2ZWw6ICJkZWJ1ZyIKICBmb3JtYXQ6ICJqc29uIgpzdGF0aWNDbGllbnRzOgotIGlkOiBleGFtcGxlLWFwcAogIHJlZGlyZWN0VVJJczoKICAtICdodHRwOi8vMTI3LjAuMC4xOjU1NTUvY2FsbGJhY2snCiAgbmFtZTogJ0V4YW1wbGUgQXBwJwogIHNlY3JldDogWlhoaGJYQnNaUzFoY0hBdGMyVmpjbVYwCi0gaWQ6IG1jdGwKICByZWRpcmVjdFVSSXM6CiAgLSAnaHR0cDovL2xvY2FsaG9zdC5tZXRhbGt1YmUubmV0OjE4MDAwL2lkZW50aXR5L2NhbGxiYWNrJwogIG5hbWU6ICdtY3RsJwogIHNlY3JldDogWlhoaGJYQnNaUzFoY0hBdGMyVmpjbVYwCiMgc3RhdGljIHBhc3N3b3JkIHRvIGxvZ2luIGludG8gZGV4CmVuYWJsZVBhc3N3b3JkREI6IHRydWUKc3RhdGljUGFzc3dvcmRzOgotIGVtYWlsOiAiYWRtaW5Ac2FuZGJveCIKICAjIGJjcnlwdCBoYXNoIG9mIHRoZSBzdHJpbmcgInBhc3N3b3JkIjogJChlY2hvIHBhc3N3b3JkIHwgaHRwYXNzd2QgLUJpbkMgMTAgYWRtaW4gfCBjdXQgLWQ6IC1mMikKICBoYXNoOiAiJDJhJDEwJDJiMmNVOENQaE9UYUdyczFIUlF1QXVlUzdKVFQ1WkhzSFN6WWlGUG0xbGVaY2s3TWM4VDRXIgogIHVzZXJuYW1lOiAiYWRtaW4iCiAgdXNlcklEOiAiMDhhODY4NGItZGI4OC00YjczLTkwYTktM2NkMTY2MWY1NDY2Igo=
   # base64 of the following config
   #
   # issuer: http://0.0.0.0:5556/dex
   # web:
   #   http: 0.0.0.0:5556
   # # See https://dexidp.io/docs/storage/ for more options
   # storage:
   #   type: memory
   # logger:
   #   level: "debug"
   #   format: "json"
   # # static password to login into dex
   # enablePasswordDB: true
   # staticPasswords:
   # - email: "admin@sandbox"
   #   # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
   #   hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
   #   username: "admin"
   #   userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: dex
    meta.helm.sh/release-namespace: default
    meta.helm.sh/release-name: "hollow-sandbox"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: dex
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: 2.36.0
    helm.sh/chart: dex-0.14.2
  name: dex
  namespace: default
type: Opaque
