---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flasher-config
  namespace: default
data:
  config.yaml: |
    log_level: debug
    app_kind: worker
    concurrency: 5
    store_kind: serverservice
