---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flasher-config
  namespace: default
data:
  config.yaml: |
    log_level: debug
    app_kind: worker
    concurrency: 5
    store_kind: serverservice
    serverservice:
      endpoint: http://serverservice:8000
      disable_oauth: true
      facility_code: dc13
    events_broker_kind: nats
    nats:
      url: nats://nats:4222
      app_name: flasher
      publisher_subject_prefix: com.hollow.sh.controllers.responses
      stream_urn_ns: hollow-controllers
      #subscribe_subjects:
      #  - com.hollow.sh.controllers.commands.>
      connect_timeout: 30s
      #creds_file:
      consumer:
        pull: true
        name: flasher
        ack_wait: 5m
        max_ack_pending: 10
        queue_group: flasher
        subscribe_subjects:
          - com.hollow.sh.controllers.commands.servers.firmware.>
        # filter_subject required to create consumer, must be unique on stream.
        filter_subject: com.hollow.sh.controllers.commands.servers.firmware.>
      stream:
        name: controllers
        subjects:
          - com.hollow.sh.controllers.commands.>
          - com.hollow.sh.controllers.responses.>
        acknowledgements: true
        duplicate_window: 5m
        retention: workQueue
