apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-service: flasher
    kind: controller
  name: flasher
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-service: flasher
  template:
    metadata:
      labels:
        k8s-service: flasher
    spec:
      terminationGracePeriodSeconds: 1200
      containers:
        - name: flasher
          image: {{ .Values.flasher.image.repository.url }}/flasher:{{ .Values.flasher.image.repository.tag }}
          imagePullPolicy: {{ $.Values.flasher.image.pullPolicy }}
          command: [
           "flasher",
           "run",
           "--outofband",
           "--store",
           "serverservice",
           "--config",
           "/etc/flasher/config.yaml",
           "--enable-pprof",
           "--log-level",
           "debug",
           "--fault-injection",
           "--facility-code",
           "{{ .Values.flasher.env.facility }}"
          ]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/flasher
            - name: nats-creds-volume
              mountPath: /etc/nats
              readOnly: true
            - mountPath: /tmp
              name: downloads-scratch
          env:
            - name: FLASHER_NATS_URL
              value: "{{ .Values.flasher.env.endpoints.nats.url }}"
            - name: FLASHER_NATS_CONNECT_TIMEOUT
              value: "{{ .Values.flasher.env.NATS_CONNECT_TIMEOUT }}"
            - name: FLASHER_NATS_KV_REPLICAS
              value: "0"
            - name: FLASHER_SERVERSERVICE_ENDPOINT
              value: "{{ .Values.flasher.env.endpoints.fleetdb.url }}"
            - name: FLASHER_SERVERSERVICE_DISABLE_OAUTH
              value: "{{ not .Values.flasher.env.endpoints.fleetdb.authenticate }}"
            - name: FLASHER_SERVERSERVICE_FACILITY_CODE
              value: "{{ .Values.flasher.env.facility }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.flasher.env.endpoints.otel.url }}"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "{{ not .Values.flasher.env.endpoints.otel.authenticate }}"
            - name: FLASHER_SERVERSERVICE_OIDC_AUDIENCE_ENDPOINT
              value: "{{ .Values.flasher.env.endpoints.fleetdb.oidc_audience_url }}"
            - name: FLASHER_SERVERSERVICE_OIDC_ISSUER_ENDPOINT
              value: "{{ .Values.flasher.env.endpoints.fleetdb.oidc_issuer_url }}"
            - name: FLASHER_SERVERSERVICE_OIDC_CLIENT_SCOPES
              value: "{{ .Values.flasher.env.endpoints.fleetdb.oidc_client_scopes }}"
            - name: FLASHER_SERVERSERVICE_OIDC_CLIENT_ID
              value: "{{ .Values.flasher.env.endpoints.fleetdb.oidc_client_id }}"
              #- name: FLASHER_SERVERSERVICE_OIDC_CLIENT_SECRET
              #  valueFrom:
              #    secretKeyRef:
              #      name: flasher-secrets
              #      key: serverservice-oidc-client-secret
            - name: FLASHER_NATS_CREDS_FILE
              value: /etc/nats/nats.creds
          securityContext:
            capabilities:
              drop:
                - NET_RAW
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            limits:
              cpu: 200m
              memory: 200M
            requests:
              cpu: 200m
              memory: 200M
          ports:
            - name: metrics-port
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            initialDelaySeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: flasher-config
        - name: nats-creds-volume
          secret:
            secretName: flasher-secrets
            items:
              - key: flasher-nats-creds
                path: nats.creds
        - name: downloads-scratch
          emptyDir: {}
      restartPolicy: Always
