apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-service: flasher
  name: flasher
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-service: flasher
  template:
    metadata:
      labels:
        k8s-service: flasher
    spec:
      containers:
        - name: flasher
          image: "{{ .Values.flasher.image.repository }}:{{ .Values.flasher.image.tag }}"
          command: [
           "flasher",
           "run",
           "--store",
           "serverservice",
           "--dry-run",
           "--config",
           "/etc/flasher/config.yaml",
           "--enable-pprof",
           "--log-level",
           "trace",
          ]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/flasher
            - name: nats-creds-volume
              mountPath: /etc/nats
          env:
            - name: FLASHER_NATS_CREDS_FILE
              value: /etc/nats/nats.creds
          resources:
            limits:
              cpu: 200m
              memory: 200M
            requests:
              cpu: 200m
              memory: 200M
      volumes:
        - name: config-volume
          configMap:
            name: flasher-config
        - name: nats-creds-volume
          configMap:
            name: flasher-nats-creds
      restartPolicy: Always
