{{- if eq .Values.knobs.use_serverservice false}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-service: fleetdb
  name: fleetdb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-service: fleetdb
  template:
    metadata:
      labels:
        k8s-service: fleetdb
    spec:
      initContainers:
        - args:
            - migrate
            - up
          env:
            - name: SERVERSERVICE_CRDB_URI
              value: postgresql://root@fleetdb-crdb:26257/defaultdb?sslmode=disable
          image: "{{ .Values.fleetdb.image.repository }}:{{ .Values.fleetdb.image.tag }}"
          name: fleetdb-migrate
          resources:
            limits:
              cpu: 200m
              memory: 200M
            requests:
              cpu: 200m
              memory: 200M
      volumes:
        - name: nats-creds-volume
          secret:
            secretName: serverservice-secrets
            items:
              - key: serverservice-nats-creds
                path: nats.creds
        - name: config-volume
          configMap:
            name: fleetdb-config
      containers:
        - env:
            - name: SERVERSERVICE_CRDB_URI
              value: postgresql://root@fleetdb-crdb:26257/defaultdb?sslmode=disable
            - name: SERVERSERVICE_OIDC_ENABLED
              value: "false"
            - name: SERVERSERVICE_NATS_URL
              value: "nats://nats:4222"
            - name: SERVERSERVICE_NATS_STREAM_PREFIX
              value: {{ .Values.serverservice.nats.publishStreamPrefix }}
            - name: SERVERSERVICE_NATS_CREDS_FILE
              value: /etc/nats/nats.creds
          volumeMounts:
            - name: nats-creds-volume
              mountPath: /etc/nats
              readOnly: true
            - name: config-volume
              mountPath: /etc/fleetdb/
          image: "{{ .Values.fleetdb.image.repository }}:{{ .Values.fleetdb.image.tag }}"
          name: fleetdb
          args:
            - serve
            # base64 key generated with,
            # $ echo "foobar1234567890abcdefghijklmno" | base64
            - --config=/etc/fleetdb/config.yaml
            - --db-encryption-driver=base64key://Zm9vYmFyMTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ubwo=
            - --oidc
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 200m
              memory: 200M
            requests:
              cpu: 200m
              memory: 200M
      restartPolicy: Always
{{- end }}
