apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-service: fleetdb-crdb
  name: fleetdb-crdb
spec:
  ports:
    - name: "26257"
      port: 26257
      targetPort: 26257
  selector:
    k8s-service: fleetdb-crdb
