{{ if .Values.fleetscheduler.enable }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-scheduler-config
  namespace: default
data:
  config.yaml: |
    log_level: {{ .Values.fleetscheduler.env.log_level }}
    store_kind: fleet-scheduler
    facility_code: {{ .Values.clusterInfo.facility }}
    fleetdb_api:
      disable_oauth: {{ .Values.fleetscheduler.env.fleetdb.disable_oauth }}
      endpoint: {{ .Values.fleetscheduler.env.fleetdb.endpoint }}
    conditionorc_api:
      disable_oauth: {{ .Values.fleetscheduler.env.conditionorc.disable_oauth }}
      endpoint: {{ .Values.fleetscheduler.env.conditionorc.endpoint }}
{{ end }}