kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-service: fleetdb
  name: fleetdb
spec:
  ports:
    - name: fleetdb
      port: 8000
      targetPort: 8000
  selector:
    k8s-service: fleetdb
