apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-service: fleetdb
  name: fleetdb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-service: fleetdb
  template:
    metadata:
      labels:
        k8s-service: fleetdb
    spec:
      initContainers:
        - args:
            - migrate
            - up
          env:
            - name: FLEETDB_CRDB_URI
              value: postgresql://root@fleetdb-crdb:26257/defaultdb?sslmode=disable
          image: {{ .Values.fleetdb.image.repository.url }}/fleetdb:{{ .Values.fleetdb.image.repository.tag }}
          imagePullPolicy: {{ $.Values.fleetdb.image.pullPolicy }}
          name: fleetdb-migrate
          resources:
            limits:
              cpu: 200m
              memory: 200M
            requests:
              cpu: 200m
              memory: 200M
      containers:
        - env:
            - name: FLEETDB_CRDB_URI
              value: postgresql://root@fleetdb-crdb:26257/defaultdb?sslmode=disable
          image: {{ .Values.fleetdb.image.repository.url }}/fleetdb:{{ .Values.fleetdb.image.repository.tag }}
          imagePullPolicy: {{ $.Values.fleetdb.image.pullPolicy }}
          name: fleetdb
          args:
            - serve
            - "--oidc={{ .Values.fleetdb.enable_oidc }}"
            # base64 key generated with,
            # $ echo "foobar1234567890abcdefghijklmno" | base64
            - --db-encryption-driver=base64key://Zm9vYmFyMTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ubwo=
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 200m
              memory: 200M
            requests:
              cpu: 200m
              memory: 200M
      restartPolicy: Always
