{{ if .Values.fleet_scheduler.enable }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-scheduler-config
  namespace: default
data:
  config.yaml: |
    log_level: {{ .Values.fleet_scheduler.env.log_level }}
    store_kind: fleet-scheduler
    facility_code: {{ .Values.fleet_scheduler.env.facility }}
    fleetdb_api:
      disable_oauth: {{ not .Values.fleet_scheduler.env.endpoints.fleetdb.authenticate }}
      endpoint: {{ .Values.fleet_scheduler.env.endpoints.fleetdb.url }}
    conditionorc_api:
      disable_oauth: {{ not .Values.fleet_scheduler.env.endpoints.conditionorc.authenticate }}
      endpoint: {{ .Values.fleet_scheduler.env.endpoints.conditionorc.url }}
{{ end }}