apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-service: flipflop
  name: flipflop
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-service: flipflop
  template:
    metadata:
      labels:
        k8s-service: flipflop
    spec:
      terminationGracePeriodSeconds: 1200
      containers:
        - name: flipflop
          image: {{ .Values.flipflop.image.repository.url }}/flipflop:{{ .Values.flipflop.image.repository.tag }}
          imagePullPolicy: {{ $.Values.flipflop.image.pullPolicy }}
          command: [
           "flipflop",
           "run",
           "--store",
           "fleetdb",
           "--config",
           "/etc/flipflop/config.yaml",
           "--enable-pprof",
           "--log-level",
           "debug",
           "--fault-injection",
           "--replica-count=1",
           "--facility-code",
           "{{ .Values.flipflop.env.facility }}"
          ]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/flipflop
            - name: nats-creds-volume
              mountPath: /etc/nats
              readOnly: true
          env:
            - name: FLIPFLOP_NATS_URL
              value: "{{ .Values.flipflop.env.endpoints.nats.url }}"
            - name: FLIPFLOP_NATS_CONNECT_TIMEOUT
              value: "{{ .Values.flipflop.env.endpoints.nats.timeout }}"
            - name: FLIPFLOP_NATS_CONSUMER_NAME
              value: "{{ .Values.flipflop.env.facility }}-flipflop"
            - name: FLIPFLOP_NATS_CONSUMER_SUBSCRIBESUBJECTS
              value: "com.hollow.sh.controllers.commands.{{ .Values.flipflop.env.facility }}.servers.serverControl"
            - name: FLIPFLOP_NATS_CONSUMER_FILTERSUBJECT
              value: "com.hollow.sh.controllers.commands.{{ .Values.flipflop.env.facility }}.servers.serverControl"
            - name: FLIPFLOP_NATS_PUBLISHERSUBJECTPREFIX
              value: "com.hollow.sh.controllers.responses.{{ .Values.flipflop.env.facility }}.servers.serverControl"
            - name: FLIPFLOP_FLEETDB_ENDPOINT
              value: "{{ .Values.flipflop.env.endpoints.fleetdb.url }}"
            - name: FLIPFLOP_FLEETDB_DISABLE_OAUTH
              value: "{{ not .Values.flipflop.env.endpoints.fleetdb.authenticate }}"
            - name: FLIPFLOP_FLEETDB_FACILITY_CODE
              value: "{{ .Values.flipflop.env.facility }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.flipflop.env.endpoints.otel.url }}"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "{{ not .Values.flipflop.env.endpoints.otel.authenticate }}"
            - name: FLIPFLOP_FLEETDB_OIDC_AUDIENCE_ENDPOINT
              value: "{{ .Values.flipflop.env.endpoints.fleetdb.oidc_audience_url }}"
            - name: FLIPFLOP_FLEETDB_OIDC_ISSUER_ENDPOINT
              value: "{{ .Values.flipflop.env.endpoints.fleetdb.oidc_issuer_url }}"
            - name: FLIPFLOP_FLEETDB_OIDC_CLIENT_SCOPES
              value: "{{ .Values.flipflop.env.endpoints.fleetdb.oidc_client_scopes }}"
            - name: FLIPFLOP_FLEETDB_OIDC_CLIENT_ID
              value: "{{ .Values.flipflop.env.endpoints.fleetdb.oidc_client_id }}"
            - name: FLIPFLOP_NATS_CREDS_FILE
              value: /etc/nats/nats.creds
          securityContext:
            capabilities:
              drop:
                - NET_RAW
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            limits:
              cpu: 200m
              memory: 200M
            requests:
              cpu: 200m
              memory: 200M
          ports:
            - name: metrics-port
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            initialDelaySeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: flipflop-config
        - name: nats-creds-volume
          secret:
            secretName: flipflop-secrets
            items:
              - key: flipflop-nats-creds
                path: nats.creds
      restartPolicy: Always
