---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flipflop-config
  namespace: default
data:
  config.yaml: |
    log_level: debug
    app_kind: worker
    concurrency: 5
    store_kind: fleetdb
    events_broker_kind: nats
    nats:
      kv_replication: 1
      app_name: flipflop
      # TODO: remove deprecated stream_urn_ns field
      stream_urn_ns: hollow-controllers
      consumer:
        pull: true
        ack_wait: 5m
        max_ack_pending: 10
        queue_group: flipflop
      stream:
        name: controllers
        subjects:
          - com.hollow.sh.controllers.commands.>
          - com.hollow.sh.controllers.responses.>
        acknowledgements: true
        duplicate_window: 5m
        retention: workQueue
