apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-service: jaeger
  name: jaeger
spec:
  ports:
    - name: "16686"
      port: 16686
      targetPort: 16686
    - name: "4317"
      port: 4317
      targetPort: 4317
    - name: "14268"
      port: 14268
      targetPort: 14268
  selector:
    k8s-service: jaeger
