kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-service: conditionorc
  name: conditionorc
spec:
  ports:
    - name: conditionorc
      port: 9002
      targetPort: 9001
      protocol: TCP
  selector:
    k8s-service: conditionorc
