kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-service: conditionorc-api
  name: conditionorc-api
spec:
  ports:
    - name: conditionorc-api
      port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    k8s-service: conditionorc-api
