apiVersion: v1
kind: ConfigMap
metadata:
  name: modeldata
data:
  modeldata.json: |
    [
      {
        "model": "X12STH-SYS",
        "manufacturer": "supermicro",
        "firmware": {
          "BMC": [
            {
              "build_date": "06/27/2022",
              "filename": "BMC_X12AST2600-F201MS_20220627_1.13.04_STDsp.bin",
              "firmware_version": "01.13.04",
              "vendor_uri": "https://www.supermicro.com/about/policies/disclaimer.cfm?SoftwareItemID=15671",
              "md5sum": "8e9d8c6bc73888379aa99793429e3a90",
              "latest": true,
              "prerequisite": false
            }
          ]
        }
      }
    ]

  nginx.conf: |
    worker_processes  3;
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;

        location /modeldata.json {
          default_type application/json;
          alias /data/modeldata.json;
        }
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: modeldata
  labels:
    app: modeldata
spec:
  selector:
    matchLabels:
      app: modeldata
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: modeldata
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: modeldata
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: modeldata-json
          configMap:
            name: modeldata
            items:
              - key: modeldata.json
                path: modeldata.json
      containers:
        - name: modeldata
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
          - name: modeldata-json
            mountPath: /data
          - name: nginx-config
            mountPath: /etc/nginx

---

apiVersion: v1
kind: Service
metadata:
  name: modeldata
spec:
  selector:
    app: modeldata
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
